apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apimgr
  name: apimgr
  namespace: axway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apimgr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apimgr
    spec:

      containers:
      - args:
        - /opt/Axway/apigateway/posix/bin/start-emt-instance
        env:
        - name: GW_DIR
          value: /opt/Axway/apigateway
        - name: GW_TRACE_DIR
          value: /opt/Axway/apigateway/trace/groups/topologylinks/emt-group-emt-service/trace
        - name: CASS_HOST
          value: external-cassandra
        - name: CASS_PORT
          value: "9042"
        - name: EMT_ANM_HOSTS
          value: anm:8090
        - name: EMT_DEPLOYMENT_ENABLED
          value: "true"
        - name: EMT_TRACE_LEVEL
          value: "INFO"
        - name: APIGW_LOG_TRACE_TO_FILE
          value: "true"
        - name: APIGW_LOG_TRACE_JSON_TO_STDOUT
          value: "true"
        - name: APIGW_LOG_OPENTRAFFIC_OUTPUT
          value: "file"
        image: assuperaxway.azurecr.io/apimgr:4.0
        imagePullPolicy: Always
        name: apimgr
        ports:
        - containerPort: 8075
          protocol: TCP
        - containerPort: 8065
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: k8sprobe
              value: liveness.apimgr
            path: /healthcheck
            port: 8075
            scheme: HTTPS
          initialDelaySeconds: 50
          periodSeconds: 15
          failureThreshold: 10
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: k8sprobe
              value: liveness.apimgr
            path: /healthcheck
            port: 8075
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/Axway/apigateway/logs/opentraffic
          name: apigw-volume
        lifecycle:
          preStop:
            exec:
              command: ["sleep","90"]
      initContainers:

      - name: init-anm
        image: busybox:1.30
        command: ['sh', '-c', 'until nc -w 3 -v anm 8090; do echo waiting for anm; sleep 2; done;']
      imagePullSecrets:
      - name: axwayacr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 101

      volumes:
        - name: apigw-volume
          persistentVolumeClaim:
            claimName: apimgr-azurefile
