apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-traffic
  name: api-traffic
  namespace: axway
spec:
  type: ClusterIP
  selector:
    app: apimgr
  ports:
  - port: 8065
    protocol: TCP
    targetPort: 8065
