apiVersion: v1
kind: Service
metadata:
  labels:
    app: apimgr
  name: apimgmt-ext
  namespace: axway
spec:
  type: ClusterIP
  selector:
    app: apimgr
  ports:
  - port: 8075
    protocol: TCP
    targetPort: 8075
